version: '3'

services:
  server:
    container_name: ms_clients
    build:
      context: .
      dockerfile: Dockerfile
    image: ms_clients
    volumes:
      - ./:/src/ms_clients
      - /src/ms_clients/node_modules
    command: yarn dev:server
    networks:
      - microsservices-prova
    depends_on:
      - mysql

  migrations:
    build:
      context: .
      dockerfile: Dockerfile
    image: ms_clients
    restart: 'no'
    command: yarn typeorm migration:run
    networks:
      - microsservices-prova
    depends_on:
      - mysql

networks:
  microsservices-prova:
    external: true
