version: '3'

services:
  app:
    container_name: 'lubycash'
    build:
      context: .
      dockerfile: Dockerfile
    image: lubycash
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules
    ports:
      - 3333:3333
    depends_on:
      - mysql

  migrations:
    build:
      context: .
      dockerfile: Dockerfile
    image: lubycash
    restart: always
    command: node ace migration:run
    networks:
      - microsservices-prova
    depends_on:
      - mysql

networks:
  microsservices-prova:
    external: true
